export const bairrosPorCidades = {
    "Canoas": [
        {id:1 ,nome: "Brigadeira", checked: false, valor: "0"},
        {id:2 ,nome: "Centro", checked: false, valor: "0"},
        {id:3 ,nome: "Estância Velha", checked: false, valor: "0"},
        {id:4 ,nome: "Fátima", checked: false, valor: "0"},
        {id:5 ,nome: "Guajuviras", checked: false, valor: "0"},
        {id:6 ,nome: "Harmonia", checked: false, valor: "0"},
        {id:7 ,nome: "Igara", checked: false, valor: "0"},
        {id:8 ,nome: "Industrial", checked: false, valor: "0"},
        {id:9 ,nome: "Marechal Rondon", checked: false, valor: "0"},
        {id:10 ,nome: "Mathias Velho", checked: false, valor: "0"},
        {id:11 ,nome: "Mato Grande", checked: false, valor: "0"},
        {id:12 ,nome: "Niterói", checked: false, valor: "0"},
        {id:13 ,nome: "Nossa Senhora das Graças", checked: false, valor: "0"},
        {id:14 ,nome: "Olaria", checked: false, valor: "0"},
        {id:15 ,nome: "Rio Branco", checked: false, valor: "0"},
        {id:16 ,nome:"São José", checked: false, valor: "0"},
        {id:17 ,nome:"São Luis", checked: false, valor: "0"}
    ],
    "Porto Alegre": [
        {id: 1 ,nome: "Aberta dos Morros", checked: false, valor: "0"},
        {id: 2 ,nome: "Agronomia", checked: false, valor: "0"},
        {id: 3 ,nome: "Anchieta", checked: false, valor: "0"},
        {id: 4 ,nome: "Arquipélago", checked: false, valor: "0"},
        {id: 5 ,nome: "Auxiliadora", checked: false, valor: "0"},
        {id: 6 ,nome: "Azenha", checked: false, valor: "0"},
        {id: 7 ,nome: "Bela Vista", checked: false, valor: "0"},
        {id: 8 ,nome: "Belém Novo", checked: false, valor: "0"},
        {id: 9 ,nome: "Belém Velho", checked: false, valor: "0"},
        {id: 10 ,nome: "Boa Vista", checked: false, valor: "0"},
        {id: 11 ,nome: "Boa Vista do Sul", checked: false, valor: "0"},
        {id: 12 ,nome: "Bom Fim", checked: false, valor: "0"},
        {id: 13 ,nome: "Bom Jesus", checked: false, valor: "0"},
        {id: 14 ,nome: "Camaquã", checked: false, valor: "0"},
        {id: 15 ,nome: "Campo Novo", checked: false, valor: "0"},
        {id: 16 ,nome: "Cascata", checked: false, valor: "0"},
        {id: 17 ,nome: "Cavalhada", checked: false, valor: "0"},
        {id: 18 ,nome: "Centro Histórico", checked: false, valor: "0"},
        {id: 19 ,nome: "Chácara das Pedras", checked: false, valor: "0"},
        {id: 20 ,nome: "Chapéu do Sol", checked: false, valor: "0"},
        {id: 21 ,nome: "Cidade Baixa", checked: false, valor: "0"},
        {id: 22 ,nome: "Coronel Aparício Borges", checked: false, valor: "0"},
        {id: 23 ,nome: "Costa e Silva", checked: false, valor: "0"},
        {id: 24 ,nome: "Cristal", checked: false, valor: "0"},
        {id: 25 ,nome: "Cristo Redentor", checked: false, valor: "0"},
        {id: 26 ,nome: "Espírito Santo", checked: false, valor: "0"},
        {id: 27 ,nome: "Extrema", checked: false, valor: "0"},
        {id: 28 ,nome: "Farrapos", checked: false, valor: "0"},
        {id: 29 ,nome: "Farroupilha", checked: false, valor: "0"},
        {id: 30 ,nome: "Floresta", checked: false, valor: "0"},
        {id: 31 ,nome: "Glória", checked: false, valor: "0"},
        {id: 32 ,nome: "Guarujá", checked: false, valor: "0"},
        {id: 33 ,nome: "Higienópolis", checked: false, valor: "0"},
        {id: 34 ,nome: "Hípica", checked: false, valor: "0"},
        {id: 35 ,nome: "Humaitá", checked: false, valor: "0"},
        {id: 36 ,nome: "Independência", checked: false, valor: "0"},
        {id: 37 ,nome: "Ipanema", checked: false, valor: "0"},
        {id: 38 ,nome: "Jardim Botânico", checked: false, valor: "0"},
        {id: 39 ,nome: "Jardim Carvalho", checked: false, valor: "0"},
        {id: 40 ,nome: "Jardim do Salso", checked: false, valor: "0"},
        {id: 41 ,nome: "Jardim Europa", checked: false, valor: "0"},
        {id: 42 ,nome: "Jardim Floresta", checked: false, valor: "0"},
        {id: 43 ,nome: "Jardim Isabel", checked: false, valor: "0"},
        {id: 44 ,nome: "Jardim Itu", checked: false, valor: "0"},
        {id: 45 ,nome: "Jardim Itu Sabará", checked: false, valor: "0"},
        {id: 46 ,nome: "Jardim Leopoldina", checked: false, valor: "0"},
        {id: 47 ,nome: "Jardim Lindóia", checked: false, valor: "0"},
        {id: 48 ,nome: "Jardim Sabará", checked: false, valor: "0"},
        {id: 49 ,nome: "Jardim São Pedro", checked: false, valor: "0"},
        {id: 50 ,nome: "Lageado", checked: false, valor: "0"},
        {id: 51 ,nome: "Lami", checked: false, valor: "0"},
        {id: 52 ,nome: "Lomba do Pinheiro", checked: false, valor: "0"},
        {id: 53 ,nome: "Mário Quintana", checked: false, valor: "0"},
        {id: 54 ,nome: "Medianeira", checked: false, valor: "0"},
        {id: 55 ,nome: "Menino Deus", checked: false, valor: "0"},
        {id: 56 ,nome: "Moinhos de Vento", checked: false, valor: "0"},
        {id: 57 ,nome: "Mont Serrat", checked: false, valor: "0"},
        {id: 58 ,nome: "Morro Santana", checked: false, valor: "0"},
        {id: 59 ,nome: "Navegantes", checked: false, valor: "0"},
        {id: 60 ,nome: "Nonoai", checked: false, valor: "0"},
        {id: 61 ,nome: "Parque Santa Fé", checked: false, valor: "0"},
        {id: 62 ,nome: "Partenon", checked: false, valor: "0"},
        {id: 63 ,nome: "Passo da Areia", checked: false, valor: "0"},
        {id: 64 ,nome: "Passo das Pedras", checked: false, valor: "0"},
        {id: 65 ,nome: "Pedra Redonda", checked: false, valor: "0"},
        {id: 66 ,nome: "Petrópolis", checked: false, valor: "0"},
        {id: 67 ,nome: "Pitinga", checked: false, valor: "0"},
        {id: 68 ,nome: "Ponta Grossa", checked: false, valor: "0"},
        {id: 69 ,nome: "Praia de Belas", checked: false, valor: "0"},
        {id: 70 ,nome: "Protásio Alves", checked: false, valor: "0"},
        {id: 71 ,nome: "Restinga", checked: false, valor: "0"},
        {id: 72 ,nome: "Rio Branco", checked: false, valor: "0"},
        {id: 73 ,nome: "Rubem Berta", checked: false, valor: "0"},
        {id: 74 ,nome: "Santa Cecília", checked: false, valor: "0"},
        {id: 75 ,nome: "Santa Maria Goretti", checked: false, valor: "0"},
        {id: 76 ,nome: "Santa Rosa de Lima", checked: false, valor: "0"},
        {id: 77 ,nome: "Santa Tereza", checked: false, valor: "0"},
        {id: 78 ,nome: "Santana", checked: false, valor: "0"},
        {id: 79 ,nome: "Santo Antônio", checked: false, valor: "0"},
        {id: 80 ,nome: "São Caetano", checked: false, valor: "0"},
        {id: 81 ,nome: "São Geraldo", checked: false, valor: "0"},
        {id: 82 ,nome: "São João", checked: false, valor: "0"},
        {id: 83 ,nome: "São José", checked: false, valor: "0"},
        {id: 84 ,nome: "São Sebastião", checked: false, valor: "0"},
        {id: 85 ,nome: "Sarandi", checked: false, valor: "0"},
        {id: 86 ,nome: "Serraria", checked: false, valor: "0"},
        {id: 87 ,nome: "Sétimo Céu", checked: false, valor: "0"},
        {id: 88 ,nome: "Teresópolis", checked: false, valor: "0"},
        {id: 89 ,nome: "Três Figueiras", checked: false, valor: "0"},
        {id: 90 ,nome: "Tristeza", checked: false, valor: "0"},
        {id: 91 ,nome: "Vila Assunção", checked: false, valor: "0"},
        {id: 92 ,nome: "Vila Conceição", checked: false, valor: "0"},
        {id: 93 ,nome: "Vila Ipiranga", checked: false, valor: "0"},
        {id: 94 ,nome: "Vila Jardim", checked: false, valor: "0"},
        {id: 95 ,nome: "Vila João Pessoa", checked: false, valor: "0"},
        {id: 96 ,nome: "Vila Nova", checked: false, valor: "0"},
        {id: 97 ,nome: "Vila São José", checked: false, valor: "0"},
    ]
}


